// Code generated by hertz generator.

package demo

import (
	"context"

	demo "github.com/SchrodingerwithCat/apiGateway/http/biz/model/demo"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// TeacherRegister .
// @router /teacher/add-student-info [POST]
func TeacherRegister(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo.Teacher
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(demo.RegisterResp)

	c.JSON(consts.StatusOK, resp)
}

// TeacherQuery .
// @router /teacher/query [GET]
func TeacherQuery(ctx context.Context, c *app.RequestContext) {
	var err error
	var req demo.QueryReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(demo.Student)

	c.JSON(consts.StatusOK, resp)
}
