// Code generated by hertz generator.

package demo

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _studentMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _registerMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _teacherMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _register0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _query0Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _sturegisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _stuqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _teacherregisterMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _teacherqueryMw() []app.HandlerFunc {
	// your code...
	return nil
}
